### ISSUE TITLE
MPI hanging

### ISSUE THREAD

**Issue by hyschive** [calab-ntu/eureka#3]

**Comment by koarakawaii** [comment]
# Eureka default UCX and OpenMPI library 
`GAMER` test using default `UCX` library and `OpenMPI` found below issues:
1. Segmentation fault during Loading input data
2. Time step too small crash
3. Runtime hanging
4. Reliable Connected error (`Local QP operation on mlx5_0:1/IB`)

# Latest UCX and OpenMPI library (before setting RUNPATH in GAMER)
### Result
Experiment (5 test runs using `UM_IC`+5 test runs using `RESTART`) with latest `UCX` library and `OpenMPI` (version can be seen [here](https://github.com/calab-ntu/psidm-halo-reconstruction/issues/16)) all passed, with 20 time step evolution (`eureka13` excluded). 

Experiment (2 test runs using `RESTART`) with latest `UCX` library and `OpenMPI` (version can be seen [here](https://github.com/calab-ntu/psidm-halo-reconstruction/issues/16)) with `eureka13` included found below issues:
1. Time step too small crash
2. Runtime hanging

i.e, **issue 4** seems to be fixed using latest library. Waiting for RAM test on `eureka13` to confirm memory problem.

### RAM test
`2021/07/07`RAM test on `eureka13` failed.

# Latest UCX and OpenMPI library(after setting RUNPATH in GAMER)
### Experiment log
`[2021/07/08]`
<br>Experiment on old branch `GAMER` hanging for once (`UM_IC` restart). After `qdel` and resubmitted, `eureka12` GPU down. Error gotten by `nvidia-smi`:
```
Unable to determine the device handle for GPU 0000:41:00.0: Unknown Error
```  
`[2021/07/08]`
<br>Experiment on latest branch `GAMER` failed at 9th of 10 tests (`Data_XXXXXX` restart), with error message below and `eureka05` down: 
```
[1625748411.529634] [eureka26:130152:0]      ucp_worker.c:481  UCX  ERROR ep 0x7fd744a2c100: error 'Endpoint timeout' on rc_mlx5/mlx5_0:1 will not be handled since no error callback is installed
[eureka26:130152:0:130152] ib_mlx5_log.c:174  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[eureka26:130152:0:130152] ib_mlx5_log.c:174  RC QP 0xc66 wqe[1808]: SEND --e [inl len 14] [rqpn 0x3038 dlid=7 sl=0 port=1 src_path_bits=0]
[1625748411.691269] [eureka30:110680:0]      ucp_worker.c:481  UCX  ERROR ep 0x7f51ee23a180: error 'Endpoint timeout' on rc_mlx5/mlx5_0:1 will not be handled since no error callback is installed
[eureka30:110680:0:110680] ib_mlx5_log.c:174  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[eureka30:110680:0:110680] ib_mlx5_log.c:174  RC QP 0x1343 wqe[174]: SEND --e [inl len 74] [rqpn 0x3043 dlid=7 sl=0 port=1 src_path_bits=0]
[1625748411.925605] [eureka25:15811:0]      ucp_worker.c:481  UCX  ERROR ep 0x7f46ba963080: error 'Endpoint timeout' on rc_mlx5/mlx5_0:1 will not be handled since no error callback is installed
[eureka25:15811:0:15811] ib_mlx5_log.c:174  Transport retry count exceeded on mlx5_0:1/IB (synd 0x15 vend 0x81 hw_synd 0/0)
[eureka25:15811:0:15811] ib_mlx5_log.c:174  RC QP 0x1904 wqe[804]: SEND --e [inl len 14] [rqpn 0x3035 dlid=7 sl=0 port=1 src_path_bits=0]
```

`[2021/07/09]`
1. `eureka12` will be checked
**Result:**
GPU tilted, see: https://github.com/calab-ntu/eureka/issues/10
2. `eureka05` error log will be checked
**Result:**
A gap between the last log of 2021/07/08 20:40 (halt) and the first log of 2021/07/09 10:06 (reboot) is confirmed. The crash (2021/07/08 20:46:51) happened inside this time gap, without obvious error message. See below ![](https://drive.google.com/uc?export=view&id=12KqO7KLOsSrUJtKUQ2g07mlyJRQi9Epp)

`[2021/07/10]`
<br>`GAMER` latest branch (commit `7cc078122fcfaedc94a5ebc9ebb493fc1c774913`) passed 10 runs with `UM_IC` and 10 runs with dumped `hdf5`. 

`[2021/07/11]`
<br>`GAMER` older branch (commit `6904479aadec0f0ad3e29f43859e4b731f461ff1`) passed 10 runs with `UM_IC` and 10 runs with dumped `hdf5`. 

`[2021/07/12]`
<br>`eureka13` still failed the RAM test. Wei-Hsuan Tzeng replaced a new CPU and restarted RAM test.

`[2021/07/13]`
<br>`eureka13` still failed the RAM test. New mother board will be changed (about 2 weeks).

`[2021/07/14]`
      1. Install latest `UCX` library under `/software/openucx`
      2. Install latest `OpenMPI` (ver 4.1.1) using GNU and Intel under `/software/openmpi/4.1.1/gnu` and `/software/openmpi/4.1.1/intel-oneapi` respectively.
      
`[2021/07/15]`
<br> Install `FFTW` libraries compiled by both GNU and Intel `OpenMPI`

`[2021/07/19]`
     1. GNU compiled `OpenMPI` passed 10 `UM_IC` and 10 `RESTART` tests
     2. Intel compiled `OpenMPI` passed 9 `UM_IC` (1 fail due to `eureka04` down) and 10 `RESTART` tests (`GAMER` dynamic shared library for MPI was not set correctly)
 
`[2021/07/19]`
     1. Recompiled both `OpenMPI` and `FFTW` by GNU and Intel compiler, to follow the naming convention for folder under `Eureka` system
     2. GNU version subjected to 5 `UM_IC` and 5 `RESTART` tests, while Intel version subjected to 10 `UM_IC` and 10 `RESTART` tests (since in the previous tests dynamic shared libraries for `GAMER` is not set correctly for Intel version)
    
`[2021/07/20]`
1. 5 tests with `UM_IC` passed for GNU compiler; however, 2 out of 5 tests for `RESTART` failed due to memory free after time evolution ended, all reported by `eureka18`
 2. Arrange `eureka18` for RAM test
 3. 5 tests for `RESTART` passed after substituting `eureka18` to `eureka28`
 4. 10 tests with `UM_IC` passed for Intel compiler; however, tests for `RESTART` failed at 2nd run due to `eureka12` GPU failure 
     ```
     Unable to determine the device handle for GPU 0000:41:00.0: Unknown Error
     ```
`[2021/07/21]`
1. 10 tests with `RESTART` passed for Intel compiler
2.  Change default MPI to version 4.1.1; change default FFTW to that compiled by OpenMPI 4.1.1
